[0m19:34:53.160850 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11395c310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114827f40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114826740>]}


============================== 19:34:53.171602 | 89f4ba27-b0ad-4502-9835-7fdba0f5d6ea ==============================
[0m19:34:53.171602 [info ] [MainThread]: Running with dbt=1.10.2
[0m19:34:53.171988 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/antoinelarcher/.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt debug', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:34:53.198977 [info ] [MainThread]: dbt version: 1.10.2
[0m19:34:53.201052 [info ] [MainThread]: python version: 3.10.4
[0m19:34:53.201409 [info ] [MainThread]: python path: /Users/antoinelarcher/Documents/git_pictet/.venv/bin/python3
[0m19:34:53.201589 [info ] [MainThread]: os info: macOS-15.5-arm64-arm-64bit
[0m19:34:54.736526 [info ] [MainThread]: Using profiles dir at /Users/antoinelarcher/.dbt
[0m19:34:54.736858 [info ] [MainThread]: Using profiles.yml file at /Users/antoinelarcher/.dbt/profiles.yml
[0m19:34:54.737028 [info ] [MainThread]: Using dbt_project.yml file at /Users/antoinelarcher/Documents/git_pictet/FIX_trading/dagster/deployments/fix_pipeline/dbt_project.yml
[0m19:34:54.737243 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m19:34:54.755779 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 1.664707, "process_in_blocks": "0", "process_kernel_time": 0.157301, "process_mem_max_rss": "98648064", "process_out_blocks": "0", "process_user_time": 0.843646}
[0m19:34:54.756605 [debug] [MainThread]: Command `dbt debug` failed at 19:34:54.756273 after 1.67 seconds
[0m19:34:54.756837 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11395c310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x114829fc0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1147df7f0>]}
[0m19:34:54.757065 [debug] [MainThread]: Flushing usage events
[0m19:34:55.544431 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:35:11.500244 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104c5c2b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106827f70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1068266e0>]}


============================== 19:35:11.503482 | a8fa2703-1e31-4072-b089-4f5f231df864 ==============================
[0m19:35:11.503482 [info ] [MainThread]: Running with dbt=1.10.2
[0m19:35:11.503961 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/antoinelarcher/.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt init', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m19:35:32.268380 [debug] [MainThread]: Starter project path: /Users/antoinelarcher/Documents/git_pictet/.venv/lib/python3.10/site-packages/dbt/include/starter_project
[0m19:35:32.274564 [info ] [MainThread]: 
Your new dbt project "pictet_fix_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m19:35:32.275084 [info ] [MainThread]: Setting up your profile.
[0m19:35:37.069275 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": true, "command_wall_clock_time": 25.617033, "process_in_blocks": "0", "process_kernel_time": 0.162605, "process_mem_max_rss": "97845248", "process_out_blocks": "0", "process_user_time": 0.84803}
[0m19:35:37.069884 [debug] [MainThread]: Command `dbt init` succeeded at 19:35:37.069692 after 25.62 seconds
[0m19:35:37.070286 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104c5c2b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1068249a0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106826da0>]}
[0m19:35:37.070565 [debug] [MainThread]: Flushing usage events
[0m19:35:37.757895 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:44:01.073294 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106e5c280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x128132290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x128131e40>]}


============================== 19:44:01.076808 | d02c4ed9-2dd9-4f41-bf5a-675bd9998843 ==============================
[0m19:44:01.076808 [info ] [MainThread]: Running with dbt=1.10.2
[0m19:44:01.077345 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': '/Users/antoinelarcher/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'static_parser': 'True', 'invocation_command': 'dbt debug', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m19:44:01.087870 [info ] [MainThread]: dbt version: 1.10.2
[0m19:44:01.088163 [info ] [MainThread]: python version: 3.10.4
[0m19:44:01.088330 [info ] [MainThread]: python path: /Users/antoinelarcher/Documents/git_pictet/.venv/bin/python3
[0m19:44:01.088652 [info ] [MainThread]: os info: macOS-15.5-arm64-arm-64bit
[0m19:44:01.232593 [info ] [MainThread]: Using profiles dir at /Users/antoinelarcher/.dbt
[0m19:44:01.232966 [info ] [MainThread]: Using profiles.yml file at /Users/antoinelarcher/.dbt/profiles.yml
[0m19:44:01.233143 [info ] [MainThread]: Using dbt_project.yml file at /Users/antoinelarcher/Documents/git_pictet/FIX_trading/dagster/deployments/fix_pipeline/dbt_project.yml
[0m19:44:01.233361 [error] [MainThread]: Encountered an error:
Internal Error
  Profile should not be None if loading profile completed
[0m19:44:01.235918 [debug] [MainThread]: Resource report: {"command_name": "debug", "command_success": false, "command_wall_clock_time": 0.20928958, "process_in_blocks": "0", "process_kernel_time": 0.182152, "process_mem_max_rss": "110444544", "process_out_blocks": "0", "process_user_time": 0.895262}
[0m19:44:01.236584 [debug] [MainThread]: Command `dbt debug` failed at 19:44:01.236500 after 0.21 seconds
[0m19:44:01.236844 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106e5c280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x128129cf0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x128697040>]}
[0m19:44:01.237094 [debug] [MainThread]: Flushing usage events
[0m19:44:01.995434 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m19:47:43.340012 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104088280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105427f40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105426830>]}


============================== 19:47:43.343119 | 7c6b5568-d357-4923-be91-48918372deb7 ==============================
[0m19:47:43.343119 [info ] [MainThread]: Running with dbt=1.10.2
[0m19:47:43.343489 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/antoinelarcher/.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run --select landing_fix', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m19:47:43.343867 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/antoinelarcher/Documents/git_pictet/FIX_trading/dagster/deployments/fix_pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:47:43.345781 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.051196918, "process_in_blocks": "0", "process_kernel_time": 0.13712, "process_mem_max_rss": "101826560", "process_out_blocks": "0", "process_user_time": 0.764048}
[0m19:47:43.346056 [debug] [MainThread]: Command `dbt run` failed at 19:47:43.345993 after 0.05 seconds
[0m19:47:43.346267 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x104088280>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1054243d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x105427f10>]}
[0m19:47:43.346448 [debug] [MainThread]: Flushing usage events
[0m19:47:44.107803 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:49:28.739039 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107058370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x120236590>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x120236140>]}


============================== 13:49:28.742477 | 5bc15bc3-55f8-446e-bf04-57aff168292f ==============================
[0m13:49:28.742477 [info ] [MainThread]: Running with dbt=1.10.2
[0m13:49:28.742869 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/antoinelarcher/.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run -s +agg_kpi_by_day +agg_kpi_by_symbole +agg_kpi_by_day', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m13:49:28.743279 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/antoinelarcher/Documents/git_pictet/FIX_trading/dagster/deployments/fix_pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:49:28.745614 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.059743416, "process_in_blocks": "0", "process_kernel_time": 0.141242, "process_mem_max_rss": "101400576", "process_out_blocks": "0", "process_user_time": 0.779894}
[0m13:49:28.746016 [debug] [MainThread]: Command `dbt run` failed at 13:49:28.745937 after 0.06 seconds
[0m13:49:28.746315 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x107058370>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1202354e0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1202365c0>]}
[0m13:49:28.746530 [debug] [MainThread]: Flushing usage events
[0m13:49:29.515024 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m13:49:39.643666 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10810c340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109436560>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109436110>]}


============================== 13:49:39.647136 | 2bcd6de3-2935-4d5a-b8f0-ce3109d4e360 ==============================
[0m13:49:39.647136 [info ] [MainThread]: Running with dbt=1.10.2
[0m13:49:39.647464 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'profiles_dir': '/Users/antoinelarcher/.dbt', 'log_path': 'logs', 'fail_fast': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run -s +agg_kpi_by_day +agg_kpi_by_symbole +agg_kpi_by_day', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:49:39.647824 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/antoinelarcher/Documents/git_pictet/FIX_trading/dagster/deployments/fix_pipeline/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:49:39.650159 [debug] [MainThread]: Resource report: {"command_name": "run", "command_success": false, "command_wall_clock_time": 0.06065, "process_in_blocks": "0", "process_kernel_time": 0.125296, "process_mem_max_rss": "102006784", "process_out_blocks": "0", "process_user_time": 0.775541}
[0m13:49:39.650545 [debug] [MainThread]: Command `dbt run` failed at 13:49:39.650477 after 0.06 seconds
[0m13:49:39.650798 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x10810c340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1094354b0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x109436590>]}
[0m13:49:39.651027 [debug] [MainThread]: Flushing usage events
[0m13:49:40.358955 [debug] [MainThread]: An error was encountered while trying to flush usage events
